# Generated by Django 5.1.6 on 2025-04-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration_weeks', models.PositiveIntegerField(default=4)),
                ('sessions_per_week', models.PositiveIntegerField(default=3)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20)),
                ('drills', models.ManyToManyField(to='drills.drill')),
            ],
        ),
    ]
